server:
  port: 10010
logging:
  level:
    com:
      taoyyz: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 120.79.141.53:8848 # nacos地址
      discovery:
        ip: 162.14.66.117
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        #          filters:
        #            - AddRequestHeader=TAOYYZ,headerrr #加入请求头
        - id: order-service-order
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: order-service-shopCart
          uri: lb://orderservice
          predicates:
            - Path=/shopCart/**
        - id: email-service
          uri: lb://emailservice
          predicates:
            - Path=/email/**
        - id: product-service
          uri: lb://productservice
          predicates:
            - Path=/product/**
        - id: product-service
          uri: lb://productservice
          predicates:
            - Path=/category/**
      #      default-filters: #默认过滤器列表对所有路由生效
      #        - AddRequestHeader=TAOYYZ,123 #对所有请求都加入请求头 #声明顺序为1
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"# 允许哪些网站的跨域请求
            #              - "http://localhost:8088"
            #              - "http://localhost:8081"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期