server:
  port: 8102
spring:
  datasource:
    url: jdbc:mysql://120.79.141.53:3307/mimile?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      # 小心springcloud里springmvc抽风，首先明确只能访问static下的页面，
      # 并且需要配置默认访问前缀为/根路径，否则访问路径就要是/开头。例如static下的index.html
      # 不配置前缀和后缀的情况下需要以/index.html访问，配置了.html后缀后可以以/index访问，配置了/前缀后直接以index访问
      suffix: ".html" #配置视图默认后缀
      prefix: "/"
    static-path-pattern: "**/**"
  main:
    banner-mode: off
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#      discovery:
#        cluster-name: HZ
logging:
  level:
    com:
      taoyyz:
        orderservice: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  client:
    config:
      default:
        connectTimeout: 3000  #单位毫秒
        readTimeout: 3000
ribbon:
  eager-load:
    enabled: true
    clients: userservice
mybatis-plus:
  global-config:
    banner: false